# Generated by Django 3.2.8 on 2021-10-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='titel',
            new_name='title',
        ),
    ]
