# Generated by Django 3.2.8 on 2021-10-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_titel_books_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'books', 'verbose_name_plural': 'books'},
        ),
    ]
